import { useState } from 'react';
import { Activity, ArrowRight, ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Code2, Columns2, EyeOff, Focus, HeartPulse, Layers3, Maximize2, Monitor, Moon, Play, Radio, RotateCcw, Settings2, ShieldCheck, Sparkles, Sun, Wifi, X, Zap } from 'lucide-react';
import { send } from '../lib/bridge';
import type { IslandController } from '../hooks/useIsland';
import { measureFrames } from '../lib/performance';
import type { FrameReport } from '../lib/performance';
import type { Theme } from '../lib/domain';
import { Island } from './Island';
import { SourceIcon, WaveMark } from './Icons';
const themes: { id: Theme; name: string; english: string; text: string }[] = [
  { id: 'ink', name: '曜石', english: 'OBSIDIAN', text: '沉静的对比，清楚的重点。' },
  { id: 'cloud', name: '云白', english: 'PORCELAIN', text: '融入白色工作站，轻而不隐。' },
  { id: 'dusk', name: '暮蓝', english: 'TWILIGHT', text: '一点蓝色，让连接更有温度。' },
];
const scenarios = [
  { id: 'report', name: '报告就绪', desc: '轻提示 · 自动收起', source: 'PACS' as const, tone: 'routine' },
  { id: 'critical', name: '检验危急值', desc: '优先展开 · 明确回执', source: 'LIS' as const, tone: 'critical' },
  { id: 'unstable', name: '病危医嘱', desc: '临床状态 · 待确认', source: 'HIS' as const, tone: 'urgent' },
  { id: 'service', name: '故障已恢复', desc: '服务反馈 · 同组聚合', source: 'IT' as const, tone: 'routine' },
];
export function Studio({ c }: { c: IslandController }) {
  const [tab, setTab] = useState<'design' | 'events' | 'contract'>('design');
  const [backClicks, setBackClicks] = useState(0);
  const [measure, setMeasure] = useState<FrameReport | null>(null);
  const [measuring, setMeasuring] = useState(false);
  const [demoRunning, setDemoRunning] = useState(false);
  const [help, setHelp] = useState(false);
  const [backdrop, setBackdrop] = useState<'workspace' | 'night'>('workspace');
  const theme = themes.find(x => x.id === c.settings.theme)!;
  const benchmark = async () => {
    setMeasuring(true); const timer = setInterval(() => c.setMode(v => v === 'compact' ? 'inbox' : 'compact'), 620);
    try { setMeasure(await measureFrames(6200)); } finally { clearInterval(timer); c.setMode('compact'); setMeasuring(false); }
  };
  const journey = async () => { if (demoRunning) return; setDemoRunning(true); await c.scenario('journey'); setTimeout(() => setDemoRunning(false), 12500); };
  return <div className="studio">
    <header className="studio-header"><a className="brand" href="#" onClick={e => { e.preventDefault(); setTab('design'); }}><span className="brand-symbol"><WaveMark/></span><span>同频<span className="brand-divider"/>Island</span><span className="brand-sub">医院数字化协作空间</span></a><nav className="studio-nav" aria-label="试验台导航"><button onClick={() => setTab('design')} className={tab === 'design' ? 'active' : ''}>原型试验台</button><button onClick={() => setTab('events')} className={tab === 'events' ? 'active' : ''}>事件与回执 <span>{c.logs.length}</span></button><button onClick={() => setTab('contract')} className={tab === 'contract' ? 'active' : ''}>接入边界</button></nav><div className="header-right"><span className="prototype-badge">PROTOTYPE <b>01</b></span><button className="studio-icon" aria-label="使用帮助" onClick={() => setHelp(!help)}><CircleHelp size={19}/></button></div></header>
    <main className="studio-main">
      <section className="intro"><div><div className="overline"><span/> LESS INTERRUPTION. MORE CONNECTION.</div><h1>不打断，<span>也不错过。</span></h1><p>让分散的信息，汇成恰到好处的协作感知。</p></div><div className="intro-actions"><span className="demo-safe"><ShieldCheck size={14}/> 全部为模拟数据</span><button className="journey-button" onClick={() => void journey()} disabled={demoRunning || c.connection !== 'online'}><Play size={15} fill="currentColor"/>{demoRunning ? '协作场景演示中' : '播放一次协作场景'}<ArrowRight size={16}/></button></div></section>
      {tab === 'design' && <div className="design-layout"><section className="canvas-column"><div className="canvas-topline"><span><Monitor size={15}/>桌面体验预览 <span className="muted-light">/ 实时交互</span></span><div className="canvas-view-toggle"><button aria-label="工作站背景" className={backdrop === 'workspace' ? 'active' : ''} onClick={() => setBackdrop('workspace')}><Sun size={13}/></button><button aria-label="夜间背景" className={backdrop === 'night' ? 'active' : ''} onClick={() => setBackdrop('night')}><Moon size={13}/></button></div></div>
        <div className={`desktop-canvas ${backdrop === 'night' ? 'night' : 'day'}`}><div className="desktop-toolbar"><span className="desktop-app-icon"><HeartPulse size={16}/></span><span>住院医生工作站</span><span className="toolbar-path">心血管内科 / 日常工作</span><div className="window-controls"><span>—</span><Maximize2 size={10}/><X size={12}/></div></div>
          <div className="workspace"><aside className="workspace-sidebar"><div className="workspace-avatar">心</div><span className="ws-side-active"><Columns2 size={19}/></span><Layers3 size={19}/><Activity size={19}/><Bell size={19}/><span className="ws-sidebar-bottom"><Settings2 size={19}/></span></aside><div className="workspace-content"><div className="ws-breadcrumb">临床工作 <span>/</span> 我的患者</div><div className="ws-heading"><h2>我的患者 <span>12</span></h2><button className="background-action" onClick={() => setBackClicks(v => v + 1)} data-testid="background-action">背景操作测试 <ArrowUpRight size={12}/></button></div><div className="ws-tabs"><span className="selected">在院患者</span><span>今日入院</span><span>待出院</span><div>心血管内科 <ChevronDown size={12}/></div></div><div className="patient-table"><div className="patient-table-head"><span>床位 / 姓名</span><span>协作状态</span><span>最新动态</span></div>{[['06','王**','重点关注','检验结果已更新'],['12','李**','常规护理','影像报告已就绪'],['18','张**','术后观察','护理记录已同步'],['21','赵**','常规护理','会诊意见待查看'],['25','刘**','出院准备','出院记录整理中']].map((r, i) => <div className="patient-table-row" key={r[0]}><span><b className="bed-number">{r[0]}</b><strong>{r[1]}</strong><small>模拟患者</small></span><span className={`ws-status status-${i}`}>{r[2]}</span><span>{r[3]}</span></div>)}</div><div className="workspace-bottom"><span><ShieldCheck size={12}/> 脱敏演示环境</span><span data-testid="background-count">背景操作 {backClicks} 次 · 预览区域可独立交互</span></div></div></div>
          <div className="island-stage"><Island c={c}/></div>
          <div className="canvas-hint"><span className="hint-line"/>{c.mode === 'compact' ? '安静待命，悬停 120ms 查看消息，单击打开中心。' : '这是可交互的灵动岛。试试确认、收起与协作脉络。'}</div>
        </div>
        <div className="canvas-bottomline"><div><span className={`live-dot ${c.connection !== 'online' ? 'offline' : ''}`}/>{c.connection === 'online' ? '模拟服务端已连接' : c.connection === 'connecting' ? '正在连接模拟服务端' : '连接已中断，正在重连'}<span className="bottom-divider"/>WebSocket → {window.__TAURI_INTERNALS__ ? 'Rust → ' : ''}Island</div><button onClick={() => { void send({ type: 'reset' }); c.setMode('compact'); }}><RotateCcw size={12}/> 重置场景</button></div>
        <section className="scenario-section"><div className="section-heading"><h2>让一条消息抵达</h2><span>选择场景，观察触达与反馈</span></div><div className="scenario-grid">{scenarios.map(s => <button key={s.id} className="scenario-card" onClick={() => void c.scenario(s.id)} disabled={c.connection !== 'online'} data-testid={`scenario-${s.id}`}><span className={`scenario-icon ${s.tone}`}><SourceIcon source={s.source} size={20}/></span><span><strong>{s.name}</strong><small>{s.desc}</small></span><ArrowUpRight size={14}/></button>)}</div><div className="scenario-foot"><span>12 条同组更新同时抵达，会发生什么？</span><button onClick={() => void c.scenario('burst')} disabled={c.connection !== 'online'}><Zap size={12}/> 测试消息聚合</button></div></section>
      </section>
      <aside className="inspector"><div className="inspector-heading"><span><Settings2 size={16}/> 体验调校</span><span>LIVE</span></div><section className="inspector-section"><div className="inspector-label"><h3>外观方向</h3><span>3 种可验证原型</span></div><div className="theme-options">{themes.map(t => <button key={t.id} className={`theme-option ${c.settings.theme === t.id ? 'selected' : ''}`} onClick={() => c.changeSettings({ theme: t.id })} data-testid={`theme-${t.id}`} aria-pressed={c.settings.theme === t.id}><span className={`theme-sample sample-${t.id}`}><WaveMark/><span/><i/></span><span className="theme-name">{t.name}<small>{t.english}</small></span><span className="theme-check">{c.settings.theme === t.id && <Check size={12}/>}</span></button>)}</div><p className="theme-caption">{theme.text}</p></section>
      <section className="inspector-section"><div className="inspector-label"><h3>动效引擎</h3><span>A / B 对照</span></div><div className="segmented"><button className={c.settings.engine === 'gsap' ? 'selected' : ''} onClick={() => c.changeSettings({ engine: 'gsap' })}>GSAP 弹簧</button><button className={c.settings.engine === 'css' ? 'selected' : ''} onClick={() => c.changeSettings({ engine: 'css' })}>原生 CSS</button></div><div className="shape-selector"><div className="segmented"><button aria-pressed={c.settings.shape === 'notch'} className={c.settings.shape === 'notch' ? 'selected' : ''} onClick={() => c.changeSettings({ shape: 'notch' })}>U 形刘海</button><button aria-pressed={c.settings.shape === 'capsule'} className={c.settings.shape === 'capsule' ? 'selected' : ''} onClick={() => c.changeSettings({ shape: 'capsule' })}>等高胶囊</button></div></div><p className="field-note motion-spec">540ms 轻回弹 · 340ms 收拢<br/>外壳先动，内容分层出现；不拉伸文字。</p></section>
      <section className="inspector-section preferences"><Toggle icon={<Focus size={17}/>} title="专注模式" description="普通消息仅计数，危急消息仍提醒" value={c.settings.focus} onChange={v => c.changeSettings({ focus: v })}/><Toggle icon={<EyeOff size={17}/>} title="隐私遮罩" description="默认不在浮层直接展示患者信息" value={c.settings.privacy} onChange={v => c.changeSettings({ privacy: v })}/><Toggle icon={<Sparkles size={17}/>} title="减少动态" description="保留信息层级，关闭形变动画" value={c.settings.reduced} onChange={v => c.changeSettings({ reduced: v })}/></section>
      <section className="inspector-section performance-panel"><div className="inspector-label"><h3><Activity size={14}/> 动效采样</h3><span>按需测量</span></div><div className="performance-values"><div><strong>{measure ? measure.averageFps : '—'}</strong><span>平均帧率</span></div><div><strong>{measure ? measure.p95Ms : '—'}<small> ms</small></strong><span>P95 帧间隔</span></div></div><button className="measure-button" disabled={measuring} onClick={() => void benchmark()}>{measuring ? '正在采样展开 / 收起过程…' : '运行一轮动效采样'}<ArrowRight size={13}/></button><p className="field-note">{measure ? `${measure.frames} 帧 · >25ms ${measure.over25ms} 帧${measure.hidden ? ' · 页面曾在后台，样本无效' : ''}` : '目标 60fps；以当前机器实测为准。'}<br/>空闲时不持续运行帧率监测。</p></section>
      <div className="inspector-bottom"><ShieldCheck size={16}/><p>显示 ≠ 收到<br/><strong>收到 ≠ 已处置</strong></p><span>DESIGNED<br/>FOR CARE</span></div></aside></div>}
      {tab === 'events' && <section className="data-panel"><div className="section-heading"><div><h2>每次抵达，都有迹可循。</h2><p>仅保留当前会话最近 80 条演示事件，不落盘患者信息。</p></div><span className="demo-safe"><Radio size={14}/>{c.items.length} 条聚合消息 · {c.todo.length} 条待确认</span></div><div className="event-stats"><span>幂等去重 <b>{c.model.duplicates}</b></span><span>格式拒绝 <b>{c.model.rejected}</b></span><span>容量告警 <b>{c.model.overflow}</b></span></div>{c.logs.length ? <div className="event-log">{c.logs.map(x => <div key={x.id}><time>{x.at}</time><span className="live-dot"/><span>{x.text}</span></div>)}</div> : <div className="large-empty"><Radio size={30}/><h3>等待第一条事件</h3><p>在原型试验台发送一条模拟消息。</p></div>}</section>}
      {tab === 'contract' && <section className="data-panel contract"><div className="overline">PROTOTYPE BOUNDARY</div><h2>一个感知入口，不是另一套临床系统。</h2><p>一期验证触达、信息层级、形变和收到回执。业务判断与处置仍留在权威源系统。</p><div className="contract-grid"><article><NetworkIcon/><h3>事件链路</h3><code>模拟服务器 → WebSocket<br/>→ Rust / 浏览器适配器<br/>→ 分级队列 → 灵动岛<br/>→ 收到回执 → 服务端确认</code></article><article><ShieldCheck/><h3>明确边界</h3><p>默认匿名展示。自动收起不是确认。服务端回执未返回，不显示成功。危急事件独立保留，不被普通消息覆盖。</p></article><article><Code2/><h3>尚未接入</h3><p>真实 HIS / LIS / PACS、SSO、设备绑定、鉴权、离线持久化、临床升级链、签名分发、锁屏联动和多屏回归。</p></article></div><div className="contract-warning">本原型不能作为危急值通知的唯一或生产渠道。请使用模拟场景验证，不要输入真实患者数据。</div></section>}
      <footer className="studio-footer"><span>SAMEWAVE / 同频 <span>·</span> 感知相连，协作自然。</span><span>Tauri 2 + React + TypeScript <span>·</span> PROTOTYPE 0.1</span></footer>
    </main>
    {help && <div className="help-backdrop" onClick={() => setHelp(false)}><section className="help-dialog" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e => e.stopPropagation()}><button className="studio-icon help-close" onClick={() => setHelp(false)} aria-label="关闭帮助"><X size={20}/></button><span className="brand-symbol"><WaveMark/></span><h2 id="help-title">从一条消息开始。</h2><p>点击下方场景卡发送消息。胶囊单击打开消息中心，悬停 120ms 预览未读消息。展开后可以查看脱敏信息、协作脉络，并确认收到。</p><p>切换三种外观和两种引擎，比较实际体验。专注模式只抑制普通消息；危急消息不会被自动确认。</p><p><kbd>Esc</kbd> 收起浮层 <span className="bottom-divider"/> <kbd>Ctrl Shift I</kbd> 打开消息中心（当前窗口）</p><button className="journey-button" onClick={() => setHelp(false)}>开始体验 <ArrowRight size={15}/></button></section></div>}
  </div>;
}
function Toggle({ icon, title, description, value, onChange }: { icon: React.ReactNode; title: string; description: string; value: boolean; onChange: (v: boolean) => void }) {
  return <div className="preference"><span className="preference-icon">{icon}</span><div><strong>{title}</strong><small>{description}</small></div><button className={`toggle ${value ? 'on' : ''}`} role="switch" aria-checked={value} aria-label={title} onClick={() => onChange(!value)}><span/></button></div>;
}
function NetworkIcon() { return <Wifi/>; }
