from pathlib import Path
root=Path(__file__).resolve().parent.parent
p=root/'src-tauri/src/clinical_window.rs';s=p.read_text(encoding='utf8')
s=s.replace('pub struct Shape{width:f64,height:f64,radius:f64,ear:f64}', 'pub struct Shape{width:f64,height:f64,radius:f64,ear:f64,#[serde(default)]polygons:Option<Vec<Vec<[f64;2]>>>}')
s=s.replace('number("/motion/expand/spring/maxWidthOvershootRatio")','number("/motion/budgets/expand")')
s=s.replace('let max_w=number(', 'let max_w=2.0*(number("/geometry/earRadius")+44.0)+number(',1)
s=s.replace('let max_h=number("/geometry/expanded/preferredMaxHeight").min(available_height*number("/geometry/expanded/maxViewportHeightRatio"));','let max_h=480.0_f64.min(available_height*0.6)+38.0;')
s=s.replace('"y":p.y}))','"y":p.y,"topReserved":p.y>window.primary_monitor().ok().flatten().map(|m|m.position().y).unwrap_or(0)}))')
s=s.replace('!(95.0..=max+extra).contains(&g.width)','!(96.0..=max+extra).contains(&g.width)')
s=s.replace('!(26.0..=number("/geometry/expanded/preferredMaxHeight")+0.001).contains(&g.height)','!(24.0..=510.0).contains(&g.height)')
s=s.replace('!(0.0..=33.0).contains(&g.radius)','!(0.0..=64.0).contains(&g.radius)')
s=s.replace('!(0.0..=number("/geometry/earRadius")).contains(&g.ear)','!(0.0..=12.0).contains(&g.ear)')
s=s.replace('return Err("Clinical geometry exceeds UI limits".into());}Ok(())','return Err("Clinical geometry exceeds UI limits".into());}\n if let Some(polys)=&g.polygons{if polys.is_empty()||polys.len()>3||polys.iter().any(|p|p.len()<4||p.len()>512||p.iter().any(|v|!v[0].is_finite()||!v[1].is_finite()||v[0]<-12.01||v[0]>g.width+72.0||v[1]<-0.01||v[1]>g.height+12.0)){return Err("Invalid bounded UI silhouette".into());}}Ok(())')
s=s.replace('let offset=(canvas as f64-g.width*scale)/2.0;let points=contour(g.width,g.height,g.radius,g.ear);','let offset=(canvas as f64-g.width*scale)/2.0;let outlines=g.polygons.clone().unwrap_or_else(||vec![contour(g.width,g.height,g.radius,g.ear)]);')
s=s.replace('for dy in -fringe..=fringe{for dx in -fringe..=fringe{','for points in &outlines{for dy in -fringe..=fringe{for dx in -fringe..=fringe{',1)
s=s.replace(' }}\n Ok(())\n}', ' }}}\n Ok(())\n}',1)
s=s.replace('phase:Option<String>,previous:Option<Shape>)->Result<bool,String>', 'phase:Option<String>,previous:Option<Shape>,polygons:Option<Vec<Vec<[f64;2]>>>)->Result<bool,String>')
s=s.replace('let target=Shape{width:body_width,height,radius,ear};','let target=Shape{width:body_width,height,radius,ear,polygons};')
s=s.replace('assert_eq!(number("/geometry/earRadius"),7.0);','assert_eq!(number("/geometry/earRadius"),10.0);')
p.write_text(s,encoding='utf8')
p=root/'src/clinical/main.tsx';s=p.read_text(encoding='utf8').replace("import './clinical.css';","import './clinical.css';\nimport './uiux.css';");p.write_text(s,encoding='utf8')
p=root/'src/clinical/useClinicalLayout.ts';s=p.read_text(encoding='utf8').replace("s.querySelectorAll('path[data-shell]').forEach(node=>node.setAttribute('d',curve.path));", "s.querySelectorAll('path[data-shell]').forEach(node=>node.setAttribute('d',node.getAttribute('data-shell')==='rim'&&shape.ear>0?curve.path.replace(/^M[^ ]+ L([^ ]+)/,'M$1'):curve.path));")
p.write_text(s,encoding='utf8')
print('Native geometry consumes validated shared contour polygons; fixed canvas retained')
